server:
  port: 9000


---

spring:
  profiles: development
server:
  port: 9001
amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: key
    secretkey: key2

---

spring:
  profiles: production

server:
  port: 0